apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notepad
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: notepad
    spec:
      containers:
      - name: notepad
        image: d8920ya/emergency-notepad:1.0
        ports:
        - containerPort: 80