apiVersion: v1
kind: ReplicationController
metadata:
  name: notepad
spec:
  replicas: 3
  selector:
    app: notepad
  template:
    metadata:
      name: notepad
      labels:
        app: notepad
    spec:
      containers:
      - name: notepad
        image: d8920ya/emergency-notepad:1.0
        ports:
        - containerPort: 80