apiVersion: v1
kind: Service
metadata:
  name: notepad
  labels:
    name: notepad
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: notepad